## Muralidhar Reddy (U64546777)

## 1. Setup

Import modules

In [1]:
import pandas as pd
from sklearn.svm import SVC
from matplotlib import pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

np.random.seed(1)

## 2. Load data & transform

In [2]:
df = pd.read_csv(r'~/Murali/DSP/week 3/RidingMowers.csv') # let's use the same data as we did in the logistic regression example
df.head(4)

Income  Lot_Size Ownership
0    60.0      18.4     Owner
1    85.5      16.8     Owner
2    64.8      21.6     Owner
3    61.5      20.8     Owner

In [3]:
df.shape

(24, 3)

In [4]:
df.Ownership.unique()

array(['Owner', 'Nonowner'], dtype=object)

### machine learning model can mostly work on numarica so tranforme the target variable Ownership 

In [5]:
df['Ownership']=pd.get_dummies(df['Ownership'],drop_first=True)

In [6]:
df.Ownership.unique()

array([1, 0], dtype=uint8)

### separate input varibale and target varibles from data set, but we not splitting into train & test because dataset is very small 

In [7]:
X = df[['Income','Lot_Size']]
y = df['Ownership']

In [8]:
print("y properties")
print(type(y))
print(y.shape)

y properties
<class 'pandas.core.series.Series'>
(24,)


### no need to use np.ravel() for y (target)  because it is in series format

In [9]:
print("Max values")
print(df.max())
print("Min values")
print(df.min())

Max values
Income       110.1
Lot_Size      23.6
Ownership      1.0
dtype: float64
Min values
Income       33.0
Lot_Size     14.0
Ownership     0.0
dtype: float64


### scaling input variables

In [10]:
SS =preprocessing.StandardScaler()
X=SS.fit_transform(X)

In [11]:
X=pd.DataFrame(X)
print(X)

           0         1
0  -0.435452 -0.231370
1   0.880582 -0.904445
2  -0.187728  1.114781
3  -0.358039  0.778243
4   0.957995  1.956125
5   2.150167  0.105168
6   2.041788 -0.567907
7   0.741237  1.451319
8   0.029030  0.441706
9   1.267650  0.778243
10 -0.899935  1.283050
11  0.648340  0.441706
12  0.338685  0.273437
13 -0.807038  0.778243
14 -0.187728 -0.736176
15 -1.302487  0.609975
16  0.803168 -0.567907
17 -0.992832 -0.567907
18 -0.466418 -1.240983
19 -0.125797 -0.231370
20 -1.085728 -1.072714
21 -1.828900 -0.063101
22 -0.899935 -2.082327
23 -0.280625 -1.745789


In [12]:
print("Max values")
print(X.max())
print("Min values")
print(X.min())

Max values
0    2.150167
1    1.956125
dtype: float64
Min values
0   -1.828900
1   -2.082327
dtype: float64


## 3. Model the data

First, let's create a dataframe to load the model performance metrics into.

In [13]:
performance = pd.DataFrame({"model": [], "Accuracy": [], "Precision": [], "Recall": [], "F1": []})

### 3.1 Fit a SVM classification model using linear kernal

In [14]:
svm_lin_model = SVC(kernel="linear")
_ = svm_lin_model.fit(X, y)

In [15]:
model_preds = svm_lin_model.predict(X)
print(model_preds)
c_matrix = confusion_matrix(y, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"linear svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

[0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]


### 3.2 Fit a SVM classification model using rbf kernal

In [16]:
svm_rbf_model = SVC(kernel="rbf", C=4, gamma='auto',probability=True)
_ = svm_rbf_model.fit(X, y)

In [17]:
model_preds = svm_rbf_model.predict(X)
print(model_preds)
c_matrix = confusion_matrix(y, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"rbf svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]


### 3.3 Fit a SVM classification model using polynomial kernal

In [18]:
svm_poly_model = SVC(kernel="poly", degree=3, coef0=.5, C=4)
_ = svm_poly_model.fit(X, y)

In [19]:
model_preds = svm_poly_model.predict(X)
print(model_preds)
c_matrix = confusion_matrix(y, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"poly svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0]


In [20]:
## 4.0 Summary

performance

model  Accuracy  Precision    Recall        F1
0  linear svm  0.833333   0.833333  0.833333  0.833333
0     rbf svm  0.875000   0.846154  0.916667  0.880000
0    poly svm  0.833333   0.785714  0.916667  0.846154

In [21]:
from sklearn.svm import __all__

In [22]:
__all__

['LinearSVC',
 'LinearSVR',
 'NuSVC',
 'NuSVR',
 'OneClassSVM',
 'SVC',
 'SVR',
 'l1_min_c']

In [23]:
import pickle
import os

In [24]:
os.getcwd()

'C:\\Users\\rmura\\Murali\\DSP\\week 3'

## dumping 2 models svm rbf ans standerscaler

In [25]:
file =open(r'C:\\Users\\rmura\\Murali\\DSP\\week 3\svm.pkl', "wb")
pickle.dump(svm_rbf_model,file)
pickle.dump(SS,file)
file.close()

In [26]:
x1=pd.DataFrame([[60,18.4]])
x1.shape

(1, 2)

In [27]:
x1=SS.fit_transform(x1)
print(x1)

[[0. 0.]]


In [28]:
s=svm_rbf_model.predict(x1)
print(s)

[0]


## A low C makes the decision surface smooth, while a high C aims at classifying all training examples correctly. gamma defines how much influence a single training example has. The larger gamma is, the closer other examples must be to be affected.

## Winning model is rbf kernel, based on f1 score